"""Contratos de persistencia y seguridad para la gestión de usuarios."""

from contextlib import AbstractContextManager
from typing import Protocol

from src.domain.entities.user import AccessToken, TokenIdentity, User


class UserRepository(Protocol):
    def transaction(self) -> AbstractContextManager[None]: ...
    def get(self, user_id: int, *, lock: bool = False) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def list(self, offset: int, limit: int) -> list[User]: ...
    def add(self, user: User) -> User: ...
    def update(self, user: User) -> User: ...
    def delete(self, user: User) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str | None) -> bool: ...


class TokenProvider(Protocol):
    def create(self, user: User) -> AccessToken: ...
    def decode(self, token: str) -> TokenIdentity: ...
